baseURL = "https://paulosales.me/"
languageCode = "pt-br"
title = "Paulo Sales"
theme="hermit"
enableEmoji = true

[author]
    name = "Paulo Sales"
    homepage = "https://paulosales.me"

[params]
    description = "Full Stack Developer. Eu crio e faço as ideias ganharem asas com coisas simples. Fala! eu sou o Paulo. É um prazer =D"
    homeSubtitle = "Full Stack Developer"
    customCSS = ["css/custom.css"]

    [[params.social]]
        name = "twitter"
        url = "https://twitter.com/paulo_dsn"

    [[params.social]]
        name = "github"
        url = "https://github.com/paulodsn"

    [[params.social]]
        name = "linkedin"
        url = "https://linkedin.com/in/paulodsn"

[menu]
    [[menu.main]]
    name = "Quem sou eu?"
    url = "quem-sou-eu"
    weight = 10
